Added slow servo down
fablab-fribourg/EggBot pull request #3
Opened 2017-11-07 21:19 UTC by gbruhin

Slow servo down should avoid the pen to bounce on the egg when going down.

2017-11-07 22:18 UTC, gaetancollaud requested changes
Thank for you submission ! Great idea to slow down the servo when touching the egg.

The servo can be reversed depending on how you build the machine (if you put the servo on the right or on the left of the pen holder).

Can you add a constant ( `#define SERVO_REVERSE false`) and invert your condition if the servo is reversed.

You can try something like this. Not sure if the xor will work though.
```
if( (servo.read() < value) ^ SERVO_REVERSE){
//...
}else{ //no need to check the condition again here
//...
}

2017-11-18 16:52 UTC, gaetancollaud approved these changes

2017-11-18 16:52 UTC, merged

2017-11-18 16:52 UTC, gaetancollaud commented
Thank you very much

2017-11-18 16:55 UTC, gbruhin commented
cool, thanks